Update ajenti

diff --git a/ajenti b/ajenti
--- a/ajenti
+++ b/ajenti
@@ -13,60 +13,87 @@
 ### END INIT INFO
 
 # Source function library
-. /lib/lsb/init-functions
+if [ -e /lib/lsb/init-functions ]; then
+    . /lib/lsb/init-functions
+
+    log_success() {
+        log_success_msg "\$1"
+    }
+
+    log_failure() {
+        log_failure_msg "\$1"
+    }
+else
+    . /etc/rc.d/init.d/functions
+
+    log_success() {
+        echo_success
+        echo "\$1"
+    }
+
+    log_failure() {
+        echo_failure
+        echo "\$1"
+    }
+fi
 
 #the service name, a python script
-SNAME=Ajenti
+NAME=Ajenti
 
 #the full path and name of the daemon program
 #Warning: The name of executable file must be identical with service name
-PROG=/usr/local/bin/ajenti-panel
+PANEL=/usr/local/bin/ajenti-panel
 
 
-# start function
+# Start the service FOO
 start() {
-    #check the daemon status first
-    if [ -f /var/lock/subsys/$SNAME ]
-    then
-        echo "$SNAME is already started!"
-        exit 0;
-    else
-        echo $"Starting $SNAME ..."
-        python $PROG &
-        [ $? -eq 0 ] && touch /var/lock/subsys/$SNAME
-        echo $"$SNAME started."
-        exit 0;
-    fi
+        echo "Starting \$NAME:"
+        export LC_CTYPE=en_US.UTF8
+
+        if pidofproc -p \$PIDFILE \$PANEL > /dev/null; then
+            log_failure "already running"
+            exit 1
+        fi
+        if \$DAEMON -d ; then
+            log_success "started"
+        else
+            log_failure "failed"
+        fi
 }
 
-#stop function
+# Restart the service FOO
 stop() {
-    echo "Stopping $SNAME ..."
-    pid=`ps -ef | grep '[p]ython $PROG' | awk '{ print $2 }'`
-    [ "$pid"X != "X" ] && kill $pid
-    rm -rf /var/lock/subsys/$SNAME
+        echo "Stopping \$NAME:"
+        if pidofproc -p \$PIDFILE \$PANEL > /dev/null; then
+            killproc -p \$PIDFILE \$PANEL
+            /bin/rm -rf \$PIDFILE
+            log_success "stopped"
+        else
+           log_failure "not running"
+        fi
 }
 
+### main logic ###
 case "$1" in
-start)
-  start
-  ;;
-stop)
-  stop
-  ;;
-reload|restart)
-  stop
-  start
-  ;;
-status)
-  pid=`ps -ef | grep '[p]ython $PROG' | awk '{ print $2 }'`
-  if [ "$pid"X = "X" ]; then
-      echo "$SNAME is stoped."
-  else
-      echo "$SNAME (pid $pid) is running..."
-  fi
-  ;;
-*)
-  echo $"\nUsage: $0 {start|stop|restart|status}"
-  exit 1
+  start)
+        start
+        ;;
+  stop)
+        stop
+        ;;
+  status)
+        if pidofproc -p \$PIDFILE \$PANEL > /dev/null; then
+            log_success "\$NAME is running"
+        else
+            log_success "\$NAME is not running"
+        fi
+        ;;
+  restart|reload|condrestart)
+        \$0 stop && sleep 2 && \$0 start
+        ;;
+  *)
+        echo $"Usage: $0 {start|stop|restart|reload|status}"
+        exit 1
 esac
+
+exit 0
