Update ajenti

diff --git a/ajenti b/ajenti
--- a/ajenti
+++ b/ajenti
@@ -76,10 +76,28 @@ stop() {
 ### main logic ###
 case "$1" in
   start)
-        start
+        echo "Starting \$NAME:"
+        export LC_CTYPE=en_US.UTF8
+
+        if pidofproc -p \$PIDFILE \$PANEL > /dev/null; then
+            log_failure "already running"
+            exit 1
+        fi
+        if \$DAEMON -d ; then
+            log_success "started"
+        else
+            log_failure "failed"
+        fi
         ;;
   stop)
-        stop
+        echo "Stopping \$NAME:"
+        if pidofproc -p \$PIDFILE \$PANEL > /dev/null; then
+            killproc -p \$PIDFILE \$PANEL
+            /bin/rm -rf \$PIDFILE
+            log_success "stopped"
+        else
+           log_failure "not running"
+        fi
         ;;
   status)
         if pidofproc -p \$PIDFILE \$PANEL > /dev/null; then
